services:
  novel-mysql:
    container_name: novel-mysql
    image: mysql:8.0.2
    restart: always
    hostname: novel-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=555371
    volumes:
      - C:/docker-apps/mysql/data:/var/lib/mysql
      - C:/docker-apps/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: mysqld --max_allowed_packet=100M
    ports:
      - "3307:3306" # 避免与宿主机的mysql 3306冲突
    networks:
      - novelnet


  xxl-job:
    container_name: novel-xxl-job
    image: xuxueli/xxl-job-admin:2.3.1
    restart: always
    hostname: novel-xxl-job-admin
    environment:
      - PARAMS=--spring.datasource.url=jdbc:mysql://novel-mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false --spring.datasource.username=root --spring.datasource.password=555371 --xxl.job.accessToken=123456
      - JAVA_OPTS=-Xmx512m
    volumes:
      - C:/docker-apps/xxl-job-adm-data/applogs:/data/applogs
    ports:
      - "8080:8080"
    depends_on:
      - novel-mysql
    networks:
      - novelnet

networks:
  novelnet:
    driver: bridge