server:
  port: 9082

# 项目配置
novel:
  # 跨域配置
  cors:
    # 允许跨域的域名
    allow-origins:
      - http://localhost:1024
      - http://localhost:8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/novel?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 555371
  data:
    # Redis 配置
    redis:
      host: 127.0.0.1
      port: 6379
      password:
  rabbitmq:
    host: host.docker.internal # docker 容器内访问宿主机的 ip，正常来说应该是公网IP或者内网IP
    port: 5672
    username: admin
    password: 123456
    virtual-host: prod
    template:
      retry:
        # 开启重试
        enabled: true
        # 最大重试次数
        max-attempts: 3
        # 第一次和第二次重试之间的持续时间
        initial-interval: "3s"

