# docker-compose.yml
version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"  # 后续可启用 HTTPS
    volumes:
      - C:/docker-apps/nginx-data/html:/usr/share/nginx/html
      - C:/docker-apps/nginx-data/conf/nginx.conf:/etc/nginx/nginx.conf
      - C:/docker-apps/nginx-data/conf/conf.d:/etc/nginx/conf.d
      - C:/docker-apps/nginx-data/logs:/var/log/nginx
    # 可选：暴露内网
    # networks:
    #   - web

# networks:
#   web:
#     external: true