services:
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"    # AMQP 端口
      - "15672:15672"  # Web 管理界面
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
      RABBITMQ_DEFAULT_VHOST: prod
    volumes:
      - C:/docker-apps/rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped